### ISSUE TITLE
Editing the payload destroys the header

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/jsonwebtoken.io#13] opened 2016-08-31 21:13 UTC
If I paste the following JWT into the tool:

> eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiIxYjFaMTdLa0xBV09UTUg4cXA2aU1SIiwiaWF0IjoxNDcyNjY0NDU0LCJpc3MiOiJodHRwczovL2FwaS5zdG9ybXBhdGguY29tL3YxL2FwcGxpY2F0aW9ucy83T2wzNzdIVTA2OGxhZ0NZazdVOVhTIiwic3ViIjoiaHR0cHM6Ly9hcGkuc3Rvcm1wYXRoLmNvbS92MS9hY2NvdW50cy80cVRYMlF5UlZoT05kNWVRcDdoVFEwIiwiZXhwIjoxNDcyNjgxNDkwLCJydGkiOiI0NmZBSE90N1laNUVvOFIyMzVQa0YifQ.hLjNfYpf3sQ1rD-Kc9Y0yaEK3TNDq6ohDvEcamM6e7Y

Which as a header like:

```
{
 "typ": "JWT",
 "alg": "HS256",
 "kid": "4VPVLB6K44RYSKRRVAB4TEBOX",
 "stt": "access"
}
```

and then edit the payload, the header is rewritten as

```
{
  "typ": "JWT",
  "alg": "HS256"
}
```

**Comment by bretterer** [comment] 2017-09-25 18:48
Duplicate of https://github.com/stormpath/jsonwebtoken.io/issues/12

**Closed by bretterer** 2017-09-25 18:48 UTC
Labels: bug
